[package]
name = "rustbellman"
version = "0.1.0"
authors = ["zTgx <747674262@qq.com>"]
edition = "2018"

[lib]
name = "rustbellman"
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
bellman = "0.10"
bls12_381 = "0.5"
